#!/bin/bash
# 00_setup.sh
# Download Hudi JARs and schema files from S3 to the EMR master node.
# Run this once before starting any benchmark.
#
# Usage: ./00_setup.sh

set -euo pipefail

S3_BASE="s3://performance-benchmark-datasets-us-west-2/hudi-bench/pavijars"
JARS_DIR="/home/hadoop/hudi-jars"
RESULTS_DIR="/home/hadoop/benchmark_results"
SPARK_HOME="/home/hadoop/spark-3.5.0-bin-hadoop3"

echo "======================================================"
echo " Hudi Benchmark Setup"
echo "======================================================"

# Create local directories
mkdir -p "$JARS_DIR"
mkdir -p "$RESULTS_DIR"

# Verify Spark installation
if [ ! -f "$SPARK_HOME/bin/spark-submit" ]; then
    echo "ERROR: spark-submit not found at $SPARK_HOME/bin/spark-submit"
    echo "       Verify the Spark path matches what was installed on this EMR cluster."
    exit 1
fi
echo "Spark: $("$SPARK_HOME/bin/spark-submit" --version 2>&1 | head -1)"

# Download Hudi JARs
echo ""
echo "Downloading Hudi JARs from S3..."
for JAR in \
    "hudi-spark3.5-bundle_2.12-0.15.0.jar" \
    "hudi-spark3.5-bundle_2.12-0.16.0-SNAPSHOT.jar" \
    "hudi-utilities-slim-spark3.5-bundle_2.12-0.15.0.jar" \
    "hudi-utilities-slim-spark3.5-bundle_2.12-0.16.0-SNAPSHOT.jar"
do
    if [ -f "$JARS_DIR/$JAR" ]; then
        echo "  [skip] $JAR (already present)"
    else
        echo "  Downloading $JAR ..."
        aws s3 cp "$S3_BASE/$JAR" "$JARS_DIR/$JAR"
    fi
done

# Download schema files
echo ""
echo "Downloading schema files from S3..."
aws s3 cp "$S3_BASE/full_schema.avsc" "$JARS_DIR/full_schema.avsc"
# no_logical_schema.avsc is generated by 01_prepare_incremental_batches.py
# and uploaded to S3 during that step; downloaded here if it already exists.
aws s3 cp "$S3_BASE/no_logical_schema.avsc" "$JARS_DIR/no_logical_schema.avsc" 2>/dev/null \
    && echo "  Downloaded no_logical_schema.avsc" \
    || echo "  [skip] no_logical_schema.avsc not yet uploaded (run 01_prepare_incremental_batches.py first)"

# Initialize write results CSV header (read results are handled by 03_read_benchmark.py)
WRITE_RESULTS="$RESULTS_DIR/write_results.csv"
if [ ! -f "$WRITE_RESULTS" ]; then
    echo "timestamp,label,table_type,schema_type,write_num,jar_version,elapsed_seconds" \
        > "$WRITE_RESULTS"
    echo "Initialized: $WRITE_RESULTS"
fi

echo ""
echo "======================================================"
echo " Setup complete."
echo "   JARs:    $JARS_DIR"
echo "   Results: $RESULTS_DIR"
echo ""
echo " Next step:"
echo "   spark-submit $SPARK_HOME/bin/spark-submit \\"
echo "     testing-logical/perf/emr/01_prepare_incremental_batches.py"
echo "======================================================"
